Controllers/BlogPostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CuaHangVHT.Data;
using CuaHangVHT.Helper;
using CuaHangVHT.ViewModels;
using AutoMapper;
using X.PagedList.Extensions;
using Microsoft.AspNetCore.Authorization;
using AspNetCoreHero.ToastNotification.Abstractions;

namespace CuaHangVHT.Controllers
{
    public class BlogPostsController : Controller
    {
        private readonly TuanStoreContext _context;
        private readonly IMapper _mapper;
        private readonly INotyfService _notyf;

        public BlogPostsController(TuanStoreContext context, IMapper mapper, INotyfService notyf)
        {
            _context = context;
            _mapper = mapper;
            _notyf = notyf;
        }

        // GET: BlogPosts
        public async Task<IActionResult> Index(int page = 1, int pageSize = 6)
        {
            var tuanStoreContext = _context.BlogPosts
                                    .Include(b => b.User)
                                    .OrderBy(b => b.IdBlogPost);
            // Phân trang dữ liệu
            var pagedResult = tuanStoreContext.ToPagedList(page, pageSize);
            return View(pagedResult); // Truyền pagedResult cho View
        }

        // GET: BlogPosts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blogPost = await _context.BlogPosts
                .Include(b => b.User)
                .FirstOrDefaultAsync(m => m.IdBlogPost == id);
            if (blogPost == null)
            {
                return NotFound();
            }

            return View(blogPost);
        }

        [Authorize(Roles = "Admin, Manager, Staff")]
        // GET: BlogPosts/Create
        public IActionResult Create()
        {
            ViewData["UserId"] = new SelectList(_context.Users, "UserId", "UserId");
            return View();
        }

        // POST: BlogPosts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.

        [ValidateAntiForgeryToken]//****Lưu Ý
        [Authorize(Roles = "Admin, Manager, Staff")]
        [HttpPost]
        public IActionResult Create(BlogVM model, IFormFile? ImgBlog)
        {
            if (model.ImgBlog != null)
            {
                
                MyUtil.UploadHinh(ImgBlog, "images/blog");
            }
            var Blog = _mapper.Map<BlogPost>(model);

            Blog.ImageUrl = model.ImgBlog.FileName.ToString();
            Blog.CreatedAt = DateTime.Now;

            _context.Add(Blog);
            _context.SaveChangesAsync();
            _notyf.Success("Tạo Bài Viết Thành Công!");
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Admin, Manager, Staff")]
        // GET: BlogPosts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blogPost = await _context.BlogPosts.FindAsync(id);
            if (blogPost == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.Users, "UserId", "UserId", blogPost.UserId);
            return View(blogPost);
        }

        // POST: BlogPosts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin, Manager, Staff")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdBlogPost,Title,Content,CreatedAt,UserId,ImageUrl")] BlogPost blogPost)
        {
            if (id != blogPost.IdBlogPost)
            {
                return NotFound();
            }

            
                try
                {
                    _context.Update(blogPost);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BlogPostExists(blogPost.IdBlogPost))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            
            ViewData["UserId"] = new SelectList(_context.Users, "UserId", "UserId", blogPost.UserId);
            return View(blogPost);
        }

        [Authorize(Roles = "Admin, Manager, Staff")]
        // GET: BlogPosts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blogPost = await _context.BlogPosts
                .Include(b => b.User)
                .FirstOrDefaultAsync(m => m.IdBlogPost == id);
            if (blogPost == null)
            {
                return NotFound();
            }

            return View(blogPost);
        }

        // POST: BlogPosts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var blogPost = await _context.BlogPosts.FindAsync(id);
            if (blogPost != null)
            {
                _context.BlogPosts.Remove(blogPost);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BlogPostExists(int id)
        {
            return _context.BlogPosts.Any(e => e.IdBlogPost == id);
        }
    }
}

Controllers/HangHoaController.cs
using CuaHangVHT.Data;
using CuaHangVHT.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Drawing;
using System.Linq;
using System.Security.Policy;
using X.PagedList.Extensions;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace CuaHangVHT.Controllers
{
    public class HangHoaController : Controller
    {
        private readonly TuanStoreContext db;

        public HangHoaController(TuanStoreContext context) { db = context; }
        public IActionResult Index(int? loai , int page = 1, int pageSize = 9)
        {
            var hangHoa = db.Products.AsQueryable();
            if (loai.HasValue)
            {
                //Loc loai
                hangHoa = hangHoa.Where(p => p.CategoryId == loai.Value).Include(p => p.OrderDetailPromotions).ThenInclude(pr => pr.Promotion); // Thêm Khuyến mãi tại đây
            }

       

            var result = hangHoa.Select(p => new HangHoaVM
            {
                MaHh = p.ProductId,
                TenHH = p.Name,
                DonGia = p.Price,
                Hinh = p.ImageUrl ?? "",
                MoTaNgan = p.Description ?? "",
                PhanTramGiamGia = p.OrderDetailPromotions.SingleOrDefault(od => od.ProductId == p.ProductId).Promotion.DiscountPercent,
            });

            // Phân trang dữ liệu
            var pagedResult = result.ToPagedList(page, pageSize);

            return View(pagedResult);
        }
        public IActionResult Search(string? tenSP) 
        {
            var hangHoa = db.Products.AsQueryable();

            if (tenSP != null)
            {
                hangHoa = hangHoa.Where(p => p.Name.Contains(tenSP)).Include(p => p.OrderDetailPromotions).ThenInclude(pr => pr.Promotion); // Thêm Khuyến mãi tại đây;
            }

            var result = hangHoa.Select(p => new HangHoaVM
            {
                MaHh = p.ProductId,
                TenHH = p.Name,
                DonGia = p.Price,
                Hinh = p.ImageUrl ?? "",
                MoTaNgan = p.Description ?? "",
                PhanTramGiamGia = p.OrderDetailPromotions.SingleOrDefault(od => od.ProductId == p.ProductId).Promotion.DiscountPercent,
            });
            return View(result);
        }

        [Authorize]
        public IActionResult Detail(int id)
        {
            var data = db.Products
                .Include(p => p.Category)
                .Include(p => p.Stocks)
                .SingleOrDefault(p => p.ProductId == id);
            if (data == null)
            {
                TempData["Message"] = $"Không tìm thấy sản phẩm có mã {id}";
                return Redirect("/404");
            }
            // Lấy stock đầu tiên hoặc theo điều kiện mong muốn (ví dụ: WarehouseId)
            var stock = data.Stocks.FirstOrDefault(s => s.ProductId ==id); // Hoặc: data.Stocks.FirstOrDefault(s => s.WarehouseId == 1);
            var size = db.ProductSizes.Where(ps => ps.ProductId == data.ProductId).Select(ps => new ProductSizeVM {Size = ps.SizeName, Quantity= ps.Quantity, IdSize = ps.ProductSizeId }).ToList();
            var result = new ChiTietHangHoaVM
            {
                MaHh = data.ProductId,
                TenHH = data.Name,
                DonGia = data.Price,
                MoTaNgan = data.Description,
                Hinh = data.ImageUrl,
                TenLoai = data.Category.Name,
                soLuong = data.Stock,
                Sizes = size,
               
            };
            return View(result);
        }
        

       
    }
}

ViewComponents/CartViewComponent.cs
using CuaHangVHT.Helper;
using CuaHangVHT.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace CuaHangVHT.ViewComponents
{
    public class CartViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
           var cart = HttpContext.Session.Get<List<CartItemVM>>(MySetting.CART_KEY) ?? new List<CartItemVM>();
            return View("CartPanel", new CartCount
            {
                Quantity = cart.Sum(p => p.SoLuong),
                Total = cart.Sum(p => p.ThanhTien)
            });
        }
    }
}

Views/Shared/_DanhSachHangHoa.cshtml
@{
    ViewData["Title"] = "_DanhSachHangHoa";
    Layout = "_LayoutSystem.cshtml";
}

@RenderSection("BreadCum", required: false)

<div class="shop-area pt-120 pb-120">
    <div class="container">
        <div class="row flex-row-reverse">
            @RenderBody()
            <div class="col-lg-3">
                <div class="sidebar-wrapper sidebar-wrapper-mrg-right">
                    <div class="sidebar-widget mb-40">
                        <h4 class="sidebar-widget-title">Tìm kiếm </h4>
                        <div class="sidebar-search">
                            <form name="SearchForm" class="sidebar-search-form" asp-action="Search" asp-controller="HangHoa">
                                <input type="search" placeholder="keywords" name="tenSP" id="searchText">
                                <button id="searchButton" onclick="SearchForm.submit()">
                                    <i class="icon-magnifier"></i>
                                </button>
                            </form>
                        </div>
                    </div>
                    <div class="sidebar-widget shop-sidebar-border mb-35 pt-40">
                        <h4 class="sidebar-widget-title">Danh Mục </h4>
                        <div class="shop-catigory">
                            @await Component.InvokeAsync("MenuLoai")
                        </div>
                    </div>
                   
                    

                    <div class="sidebar-widget shop-sidebar-border pt-40">
                        <h4 class="sidebar-widget-title">Phổ Biến</h4>
                        <div class="tag-wrap sidebar-widget-tag">
                            <a href="#">Áo Khoác</a>
                            <a href="#">Quần</a>
                            <a href="#">Mũ</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CuaHangVHT</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CuaHangVHT.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CuaHangVHT</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CuaHangVHT - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LayoutSystem.cshtml
<!doctype html>
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>tUan Shop</title>
    <meta name="robots" content="noindex, follow" />
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="~/assets/images/logo/LogoWeb.svg">

    <!-- All CSS is here
    ============================================ -->

    <link rel="stylesheet" href="~/assets/css/vendor/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/css/vendor/simple-line-icons.css">
    <link rel="stylesheet" href="~/assets/css/vendor/elegant.css">
    <link rel="stylesheet" href="~/assets/css/vendor/linear-icon.css">
    <link rel="stylesheet" href="~/assets/css/plugins/nice-select.css">
    <link rel="stylesheet" href="~/assets/css/plugins/easyzoom.css">
    <link rel="stylesheet" href="~/assets/css/plugins/slick.css">
    <link rel="stylesheet" href="~/assets/css/plugins/animate.css">
    <link rel="stylesheet" href="~/assets/css/plugins/magnific-popup.css">
    <link rel="stylesheet" href="~/assets/css/plugins/jquery-ui.css">
    <link rel="stylesheet" href="~/assets/css/style.css">
 



    @RenderSection("Styles", required: false)
</head>

<body>

    <div class="main-wrapper">
        <header class="header-area transparent-bar section-padding-1">
            <div class="container-fluid">
                <div class="header-large-device">
                    <div class="header-bottom">
                        <div class="row align-items-center">
                            <div class="col-xl-2 col-lg-2">
                                <div class="logo">
                                    <a asp-controller="Home" asp-action="Index"><img style="width:100px; height:auto; margin-left:20px;" src="~/assets/images/logo/LogoWeb.svg" alt="logo"></a>
                                </div>
                            </div>
                            <div class="col-xl-8 col-lg-7">
                                <div class="main-menu main-menu-padding-1 main-menu-lh-1">
                                    <nav>
                                        <ul>
                                            <li>
                                                <a asp-controller="Home" asp-action="Index">Trang Chủ </a>

                                            </li>
                                            <li>
                                                <a asp-controller="HangHoa" asp-action="Index">Sản Phẩm </a>
                                                <ul class="mega-menu-style mega-menu-mrg-1">
                                                    <li>
                                                        <ul>
                                                            <li >
                                                                <a class="dropdown-title" style="padding-bottom:2px;">Tất cả sản phẩm</a>
                                                                @await Component.InvokeAsync("MenuLoai")
                                                            </li>
                                                            
                                                           
                                                            <li >
                                                                <a style="padding-right: 20px;" ><img style="width: 250px; height: auto; object-fit:cover" src="~/assets/images/banner/BST1.jpg" alt=""></a>
                                                            </li>
                                                        </ul>
                                                    </li>
                                                </ul>
                                            </li>
                                            <li>
                                                <a asp-controller="Home" asp-action="About">Về Tôi </a>

                                            </li>
                                            <li>
                                                <a asp-controller="BlogPosts" asp-action="Index">BLOG </a>

                                            </li>
                                            <li><a asp-controller="Home" asp-action="Contact">Liên Hệ </a></li>
                                            @if ((!User.IsInRole("Customer")) && User.Identity.IsAuthenticated)
                                            {
                                                <li><a asp-area="Admin" asp-controller="Home" asp-action="Index">  <i class="icon-arrow-left-circle"></i> Đến Trang Admin </a></li>
                                            }
                                            
                                        </ul>
                                    </nav>
                                </div>
                            </div>
                         
                            <div class="col-xl-2 col-lg-3">
                                <div class="header-action header-action-flex header-action-mrg-right">

                                    <div class="same-style-2">
                                        <a asp-controller="TaiKhoan" asp-action="Dangnhap"><i class="icon-user"></i></a>
                                        @if (User.Identity.IsAuthenticated)
                                        {
                                            <a style="font-size:15px;" asp-controller="TaiKhoan" asp-action="Profile">
                                                <span >Hello, @User.Identity.Name!</span>
                                                
                                            </a>
                                        }
                                    </div>

                                    @await Component.InvokeAsync("Cart")
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="header-small-device small-device-ptb-1">
                    <div class="row align-items-center">
                        <div class="col-5">
                            <div class="mobile-logo">
                                <div class="logo">
                                    <a asp-controller="Home" asp-action="Index"><img style="width:100px; height:auto; margin-left:20px;" src="~/assets/images/logo/LogoWeb.svg" alt="logo"></a>
                                </div>
                            </div>
                        </div>
                       
                    </div>
                </div>
            </div>
        </header>

        <div>
            @RenderBody()
        </div>

        <div class="subscribe-area bg-gray pt-50 pb-50">
            <div class="container">
                <div class="row">
                    <div class="col-lg-5 col-md-5">
                        <div class="section-title">
                            <h2>Liên hệ với chúng tôi:</h2>
                            <p>Mọi góp ý xin gửi về địa chỉ này:</p>
                        </div>
                    </div>
                    <div class="col-lg-7 col-md-7">
                        <div id="mc_embed_signup" class="subscribe-form">
                            <form id="mc-embedded-subscribe-form" class="validate subscribe-form-style" novalidate="" target="_blank" name="mc-embedded-subscribe-form" method="post" action="https://devitems.us11.list-manage.com/subscribe/post?u=6bbb9b6f5827bd842d9640c82&amp;id=05d85f18ef">
                                <div id="mc_embed_signup_scroll" class="mc-form">
                                    <input class="email" type="email" required="" placeholder="gửi góp ý của bạn tại đây" name="EMAIL" value="">
                                    <div class="mc-news" aria-hidden="true">
                                        <input type="text" value="" tabindex="-1" name="b_6bbb9b6f5827bd842d9640c82_05d85f18ef">
                                    </div>
                                    <div class="clear">
                                        <input id="mc-embedded-subscribe" class="button" type="submit" name="subscribe" value="Gửi">
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <footer class="footer-area bg-gray pb-10">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-md-6">
                        <div class="contact-info-wrap">
                            <div class="footer-logo">
                                <a asp-controller="Home" asp-action="Index"><img style="width:150px; height:100px;" src="~/assets/images/logo/LogoWeb.svg" alt="logo"></a>
                            </div>
                            <div class="single-contact-info">
                                <span>Địa chỉ liên hệ:</span>
                                <p>Số 06, Trần Văn Ơn, Phú Hòa, Thủ Dầu Một, Bình Dương</p>
                            </div>
                            <div class="single-contact-info">
                                <span>Số điện thoại:</span>
                                <p>0123456789</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <div class="footer-right-wrap">
                            <div class="footer-menu">
                                <nav>
                                    <ul>
                                        <li><a asp-controller="Home" asp-action="Index">Trang Chủ</a></li>
                                        <li><a asp-controller="HangHoa" asp-action="Index">Sản Phẩm</a></li>
                                        <li><a asp-controller="Home" asp-action="About">Về Tôi </a></li>
                                        <li><a asp-controller="BlogPosts" asp-action="Index">Blog</a></li>
                                        <li><a asp-controller="Home" asp-action="Contact">Liên Hệ</a></li>
                                    </ul>
                                </nav>
                            </div>
                            <div class="social-style-2 social-style-2-mrg">
                                <a ><i class="social_twitter"></i></a>
                                <a ><i class="social_facebook"></i></a>
                                <a ><i class="social_instagram"></i></a>
                           
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </footer>
    
        
        
    </div>

    <!-- All JS is here
    ============================================ -->

    <script src="~/assets/js/vendor/modernizr-3.11.7.min.js"></script>
    <script src="~/assets/js/vendor/jquery-v3.6.0.min.js"></script>
    <script src="~/assets/js/vendor/jquery-migrate-v3.3.2.min.js"></script>
    <script src="~/assets/js/vendor/popper.min.js"></script>
    <script src="~/assets/js/vendor/bootstrap.min.js"></script>
    <script src="~/assets/js/plugins/slick.js"></script>
    <script src="~/assets/js/plugins/jquery.syotimer.min.js"></script>
    <script src="~/assets/js/plugins/jquery.nice-select.min.js"></script>
    <script src="~/assets/js/plugins/wow.js"></script>
    <script src="~/assets/js/plugins/jquery-ui.js"></script>
    <script src="~/assets/js/plugins/magnific-popup.js"></script>
    <script src="~/assets/js/plugins/sticky-sidebar.js"></script>
    <script src="~/assets/js/plugins/easyzoom.js"></script>
    <script src="~/assets/js/plugins/scrollup.js"></script>
    <script src="~/assets/js/plugins/ajax-mail.js"></script>
    <!-- Main JS -->
    <script src="~/assets/js/main.js"></script>
    <!--Jquery-->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js"></script>
    <!--CKeditor-->
    <script src="https://cdn.ckeditor.com/4.16.2/standard/ckeditor.js"></script>


    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://www.gstatic.com/dialogflow-console/fast/messenger/bootstrap.js?v=1"></script>
    <df-messenger intent="WELCOME"
                  chat-title="tUan_Store"
                  agent-id="7c165db9-d1ae-46a1-930e-4e7bb6a28bdf"
                  language-code="en"></df-messenger>
    @await Component.InvokeAsync("Notyf")
    @RenderSection("Scripts", required: false)
   
</body>

</html>

Views/Shared/_LayoutSystem2.cshtml
@{
    ViewData["Title"] = "_DanhSachHangHoa";
    Layout = "_LayoutSystem.cshtml";
}

@RenderSection("BreadCum", required: false)

@RenderBody();